# Generated by Django 4.2.7 on 2024-09-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='CustomUser',
            new_name='user',
        ),
    ]
