# Generated by Django 5.1.1 on 2024-10-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='allowed_imports',
            field=models.TextField(blank=True, help_text='space-seperated list of allowed imports', null=True),
        ),
    ]
