# Generated by Django 5.1.1 on 2025-01-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_problem_allowed_imports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='solved_count',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
